---
-
  hosts: localhost
  tasks:
    - name: ansible create directory example
      file:
        path: /home/ubuntu/devops_directory
        state: directory
    - name: ansible create directory example
      file:
        path: /home/ubuntu/devops_directory/vivek.txt
        state: touch
